/anchor/anchor:
  ros__parameters:
    position:
      -x: 0.0
      -y: 0.0
      -z: 0.0
    number_of_nodes: 5
/rover1/rover:
  ros__parameters:
    position:
      -x: 1.0
      -y: 1.0
      -z: 0.0
    index: 1
    dists: [0.7,0.0,1.0,1.4,1.0]
/rover2/rover:
  ros__parameters:
    position:
      -y: 1.0
      -z: 0.0
      -x: -1.0
    index: 2
    dists: [0.7,1.0,0.0,1.0,1.4]
/rover3/rover:
  ros__parameters:
    position:
      -x: 1.0
      -y: -1.0
      -z: 0.0
    index: 3
    dists: [0.7,1.4,1.0,0.0,1.0]
/rover4/rover:
  ros__parameters:
    position:
      -x: -1.0
      -y: -1.0
      -z: 0.0
    index: 4
    dists: [0.7,1.0,1.4,1.0,0.0]

